<!DOCTYPE html>
<html>
<head>

	<title>asplForm Demo</title>	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">	

	<!-- jQuery  & aspLite JS -->
	<script src="asplite/jquery.js"></script>
	<script>var aspLiteAjaxHandler='default.asp'</script>
	<script src="asplite/asplite.js"></script>	
	
	<!-- Bootstrap CSS and JS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</head>
<body>
	<main class="container asplForm p-3" id="main">
	
	</main>		
</body>

</html>