<!DOCTYPE html>
<html>
<head>

	<title>asplForm Demo</title>
	
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width,initial-scale=1">	

	<!-- jQuery  & aspLite JS -->
	<script src="asplite/jquery.js"></script>
	<script>var aspLiteAjaxHandler='default.asp'</script>
	<script src="asplite/asplite.js"></script>


</head>
<body>

<header id="myheader" class="asplForm"></header>

<main>
	<article id="myarticle" class="asplForm"></article>
</main>

<footer id="myfooter" class="asplForm"></footer>

</body>
</html>